### ISSUE TITLE
Advanced options - needs an out of band switch

### ISSUE THREAD

**Issue by bbusenius** [hahnicity/MEGAndroid#13]
A switch is needed for "Out of band". This should default to"on".

**Comment by bbusenius** [comment]
Can someone remind me what the functionality is here? The work plan has this listed as SMS or Facebook. What does this toggle actually control?

**Comment by thompsonm-ANL** [comment]
I think this was supposed to be a preference to attempt to verify the sender's identity via out of band channel, where we can use either SMS or Facebook or attempt both.  User authentication is a huge issue that we have barely touched yet, but this should incorporate trust levels (in my mind in person/NFC is highest, SMS second, Facebook/Social Media lowest... not sure where we would fit in web of trust... things to think about).

**Comment by bbusenius** [comment]
I'm closing this out. After some discussion we believe it's better to handle this with address book functionality.
