### ISSUE TITLE
Post installation page needs specs 

### ISSUE THREAD

**Issue by bbusenius** [hahnicity/MEGAndroid#15]
From the work plan document: 

> - You're installed Page (same as "home" when you open app) 
>   --- Description of how to use the app

None of this is represented in the design comp. We need to further spec this out. How long is the description? Is it gone when the user revisits the home page? At one point we had talked about a video here. 

What is the home page in this context? Is it the screen you see when the app is launched and you still need to sign in or is it the screen you see when you're logged in?

**Comment by JoshuaLyle** [comment]
This is reflected in the latest comp and has been completed in the latest login screen.
