### ISSUE TITLE
All screens - top bar is the wrong color

### ISSUE THREAD

**Issue by bbusenius** [hahnicity/MEGAndroid#21]
The uppermost bar, where phone information is shown, is black. It should match the comps.

**Comment by JoshuaLyle** [comment]
This was related to #20 and has been fixed with the theme settings

**Comment by bbusenius** [comment]
This is still black on mine. 

![screenshot_20161221-202816](https://cloud.githubusercontent.com/assets/7826429/21413461/fd2a0ffc-c7bc-11e6-8b28-2cdc0382419f.png)

**Comment by JoshuaLyle** [comment]
Misread what bar you were talking about. It's been changed to green in 3c2c86398b766979a9d93b47c8d808f60207b6e8

**Comment by bbusenius** [comment]
Ah, so close. It should be #00796B.

**Comment by JoshuaLyle** [comment]
You would think that I didn't read the comp at all :-|. It should be correct in c9d4d2d.

I would like to throw in my 2 cents that I think it looks better with the matching green I had earlier but it matches the comps now.

I'll let you close this one.
