### ISSUE TITLE
General instability and crashing

### ISSUE THREAD

**Issue by bbusenius** [hahnicity/MEGAndroid#26]
It looks like my fix for #5 destabilized the qrcode scanner. This is probably due to a dependency upgrade. 

Symptoms:
1. Completely uninstall and reinstall the app. The app should launch and function properly.
2. Complete the installation screen. 
3. When the barcode scanner comes up, after installation, the app will crash. 
4. After the first crash, the app will continue to crash forever, every time it is launched. A complete uninstall is necessary.

**Comment by bbusenius** [comment]
This definitely looks related to the dependency upgrade from 

```
compile 'com.android.support:appcompat-v7:24.0.0-alpha2'
compile 'com.android.support:design:23.4.0'
```

to 

```
compile 'com.android.support:design:24.2.0'
compile 'com.android.support:appcompat-v7:24.2.0'
```

**Comment by bbusenius** [comment]
Also, I'm now unsure that this is related to the qrcode scanner. It might just be crashing in a general manner. So far I haven't been able to glean anything useful from the logs.

**Comment by bbusenius** [comment]
The upgrade to AppCompat 24.2.0 was a bigger deal than I anticipated. AppCompat depends on the [support-v4 library which has been split into separate modules](https://developer.android.com/topic/libraries/support-library/features.html) in version 24.2.0. I've been attempting to resolve this by following [the steps outlined on this site.](https://guides.codepath.com/android/Migrating-to-the-AppCompat-Library). So far I haven't been successful.

**Comment by JoshuaLyle** [comment]
Please check that this still happens in the latest version. The only problem I have encountered is that autofocus needs to be delayed so that it doesn't attempt to start before the camera starts. Otherwise, I have had no crashes since making this adjustment.

**Comment by bbusenius** [comment]
That seemed to clear it up!
