### ISSUE TITLE
Advanced options - Revoking the PGP Key doesn't give the user feedback

### ISSUE THREAD

**Issue by bbusenius** [hahnicity/MEGAndroid#7]
Some kind of feedback for the user is needed here. There's no way for the user to tell that a revoke process has been initiated.

**Comment by bbusenius** [comment]
In the comp there is an overlay box that says:

> Irreversible Action
> This action will enable a 2-step verification process to permanently disable your private key. This cannot be undone, however, you may create a new key when the process is complete.

This dialog has the option to Decline or Accept. Refer to the comp for more information.

**Comment by JoshuaLyle** [comment]
A popup message lets the user know the conformation email has been sent. When the phone receives confirmation over GCM, it updates all fields immediately. I'm considering this closed
